config/routes.rb
ImmediateShare::Application.routes.draw do
  constraints(:id =>/\d+/) do
    root :to => 'share_infos#index'

    match "gate(/index)" => "gate#index", :via => :get, :as => :gate
    post "gate/login", :as => :login
    post "gate/logout", :as => :logout
    get "gate/register", :as => :register
    post "gate/create"

    scope :module => "admin" do
      scope "/admin" do
        resources :users do
          member do
            put "change_admin"
          end
        end
      end
    end

    resources :share_infos, :only => [:index, :new]

    match "share_infos/share_images/upload" => "share_infos/share_images#upload", :as=>:upload
    scope :module => "share_infos" do
      scope "/share_infos" do
        resources :share_texts, :as => :texts, :only =>[:new, :create]
        resources :share_images, :as => :images, :only => [:new, :create, :show]
        resources :share_videos, :as => :videos, :only => [:new, :create]
        resources :share_links, :as => :links, :only => [:new, :create]
      end
    end

    resources :friendships, :only => [:index, :destroy] do
      collection do
        get "search"
      end
      member do
        post "ask_for_friendship", :as => :ask
        post "agree_with_friendship", :as => :agree
      end
    end
    resources :individuals, :only => [:show, :edit, :update]
    scope :module => "individuals" do
      scope "/individuals" do
        resources :avatars, :as => :avatars, :only =>[:edit, :update, :create]
        resources :temps, :as => :temps, :only =>[:new, :create, :update], :path_names => {:new=>:crop}
      end
    end
    resources :comments, :only =>[:new, :create]
    resources :replies, :only =>[:new, :create]
    resources :system_messages, :only => [:index], :path_names => {:index => "unread"} do
      collection do
        get "all_messages", :as => :all
      end
      member do
        post "ignore"
      end
    end
  end

end

app/controllers/individuals/avatars_controller.rb
class Individuals::AvatarsController < ApplicationController
  #before_filter :get_current_user, :authenticate, :get_system_message
  #(in application_controller)
 
  def edit
    @user = User.find_by_id(params[:id])
    if @user != @current_user
      flash[:error] = "you do not have the authority to modify this page"
      redirect_to(:back)
    end
  rescue ActionController::RedirectBackError
    redirect_to(individual_path(@current_user))
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user == @current_user && @user.update_attributes(params[:user])
      flash[:success] = "update avatar successfully"
      redirect_to(individual_path(@user))
    else
      flash[:error] = "failed to update your avatar, please try again"
      render(:action=>"edit")
    end
  end

end

app/controllers/individuals/temps_controller.rb
class Individuals::TempsController < ApplicationController
  #before_filter :get_current_user, :authenticate, :get_system_message
  #(in application_controller)
 
  def new
    if @current_user.temp.blank?
      @temp = Temp.new
    else
      @temp = @current_user.temp
    end
  end

  def update
    @temp = Temp.find_by_id(params[:id])
    if @temp.user_id == @current_user.id && \
      @temp.update_attributes(params[:temp])
      flash[:success] = "update avatar successfully"
      redirect_to(individual_path(@current_user))
    else
      flash[:error] = "failed to update your avatar, please try again"
      redirect_to(:action=>"new")
    end
  end

  def create
    @temp = Temp.find_by_user_id(@current_user.id)
    @temp.delete if @temp
    @temp = Temp.new(params[:temp])
    @temp.user_id = @current_user.id
    respond_to do |format|
      if @temp.save()
        format.js do
          responds_to_parent do
            render :layout => false
          end
        end
      else
        format.js do
          responds_to_parent do
            render :js=>"$(\"<div class='alert-box error'>failed to update your avatar, please try again</div>\").prependTo('body');"
          end
        end
      end
    end
  end
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  #before_filter :get_current_user, :authenticate, :get_system_message
  #(in application_controller)

  # GET /individuals/1
  # GET /individuals/1.json
  def show
    if @current_user.id == params[:id].to_i
      @user = @current_user
    else
      @user = @current_user.friends.find_by_id(params[:id])
    end
    if @user
      @friendships = @user.friendships
    else
      flash[:error] = "you don't have such a friend"
      redirect_to(:back)
    end
  rescue ActionController::RedirectBackError
    redirect_to(root_path)
  end

  # GET /individuals/1/edit
  def edit
    unless @current_user.id == params[:id].to_i
      flash[:error] = "You do not have enough authority to edit this file"
    end
    @user = @current_user
  end


  # PUT /individuals/1
  # PUT /individuals/1.json
  def update
    if @current_user.id == params[:id].to_i && \
      @current_user.update_attributes(params[:user])
      flash[:success] = "profile was successfully updated"
      redirect_to individual_path(@current_user.id)
    else
      flash[:error] = "update error, please try again"
      @user = @current_user
      render(:action => "edit")
    end
  end
end

app/helpers/individuals/avatars_helper.rb
module Individuals::AvatarsHelper
end

app/helpers/individuals/temp_helper.rb
module Individuals::TempHelper
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/avatars/_choose_system_avatars.html.erb
<div class="secondary_title">Click one as your avatar</div>
<div class="row">
  <div class="eight columns centered">
<div class="system_avatars">
  <% 1.upto(User.system_default_avatar_num).each do |i| %>
    <% if i % 3 == 1 %>
      <ul class="block-grid three-up" 
        style="border-top:thin dotted #CCCCCC; padding-top:2%;">
    <% end %>
    <li>
    <%= form_tag(avatar_path(@current_user), :method=>:put) do %>
      <%=hidden_field_tag("user[avatar_file_name]",
                          "system_default_avatar(#{i}).png")%>
      <%= image_submit_tag("avatar/system_default_avatar(#{i}).png",:width=>120) %>
    <% end %>
    </li>
    <% if i % 3 == 0 %>
      </ul>
    <% end %>
  <% end %>
</div>
  </div>
</div>

app/views/individuals/avatars/create.html.erb
<h1>Individuals::Avatars#create</h1>
<p>Find me in app/views/individuals/avatars/create.html.erb</p>

app/views/individuals/avatars/edit.html.erb
<%= page_title("Choose Avatar") %>

<div class="row">
<div class="ten columns">
<%= render("choose_system_avatars") %>
</div>
<div class="two columns">
<div class="heads_up_green">
you don't like this avatar? Perhaps you would like to <%= link_to("upload and crop", new_temp_path) %>
</div>
</div>
</div>

app/views/individuals/avatars/update.html.erb
<h1>Individuals::Avatars#update</h1>
<p>Find me in app/views/individuals/avatars/update.html.erb</p>