config/routes.rb
ImmediateShare::Application.routes.draw do
  constraints(:id =>/\d+/) do
    root :to => 'share_infos#index'

    match "gate(/index)" => "gate#index", :via => :get, :as => :gate
    post "gate/login", :as => :login
    post "gate/logout", :as => :logout
    get "gate/register", :as => :register
    post "gate/create"

    scope :module => "admin" do
      scope "/admin" do
        resources :users do
          member do
            put "change_admin"
          end
        end
      end
    end

    resources :share_infos, :only => [:index, :new]

    match "share_infos/share_images/upload" => "share_infos/share_images#upload", :as=>:upload
    scope :module => "share_infos" do
      scope "/share_infos" do
        resources :share_texts, :as => :texts, :only =>[:new, :create]
        resources :share_images, :as => :images, :only => [:new, :create, :show]
        resources :share_videos, :as => :videos, :only => [:new, :create]
        resources :share_links, :as => :links, :only => [:new, :create]
      end
    end

    resources :friendships, :only => [:index, :destroy] do
      collection do
        get "search"
      end
      member do
        post "ask_for_friendship", :as => :ask
        post "agree_with_friendship", :as => :agree
      end
    end
    resources :individuals, :only => [:show, :edit, :update]
    scope :module => "individuals" do
      scope "/individuals" do
        resources :avatars, :as => :avatars, :only =>[:edit, :update, :create]
        resources :temps, :as => :temps, :only =>[:new, :create, :update], :path_names => {:new=>:crop}
      end
    end
    resources :comments, :only =>[:new, :create]
    resources :replies, :only =>[:new, :create]
    resources :system_messages, :only => [:index], :path_names => {:index => "unread"} do
      collection do
        get "all_messages", :as => :all
      end
      member do
        post "ignore"
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shares, :class_name => "ShareInfo", :dependent => :destroy,
           :foreign_key => :from
  has_many :recieves_and_tos, :dependent => :destroy
  has_many :recieves,
           :through => :recieves_and_tos, :source => :share_info
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships
  has_many :comments
  has_many :replies
  has_many :system_message_sendeds, :class_name => "SystemMessage", 
           :foreign_key => :from
  has_many :system_message_recieveds, :class_name => "SystemMessage",
           :foreign_key => :to
  has_one :temp, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  validates :password_confirmation, :presence => true,
            :if => "self.hashed_password == nil" 
  validates :email, :email_format => true, :presence => true
  validates :avatar_file_name, :presence => true

  attr_accessible :name, :password, :password_confirmation, :email,
                  :avatar_file_name
  
  before_create :get_random_system_default_avatar


  attr_accessor :password_confirmation
  def password
    return @password
  end
  def password= pwd
    @password = pwd
    return if pwd.blank?
    create_new_salt()
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end
  def self.authenticate? name, pwd
    user = User.find_by_name(name)
    res = false
    if user
      hashed_password = User.encrypted_password(pwd, user.salt)
      if hashed_password == user.hashed_password
        res = true
      end
    end
    return res
  end
  def self.exit? id
    user = User.find_by_id(id)
    if user
      return true
    else
      return false
    end
  end

  #where avatar store
  def self.dirname
    return Rails.root.join("public","assets","avatar").to_s
  end
  def avatar_url
    return "avatar/" + self.avatar_file_name
  end
  def self.system_default_avatar_num
    return 12
  end


  private
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  def self.encrypted_password pwd, salt
    string = pwd + salt
    return Digest::SHA1::hexdigest(string)
  end
  def get_random_system_default_avatar
    self.avatar_file_name = "system_default_avatar(#{get_random()}).png"
  end
  def get_random
    return (rand*100).floor % User.system_default_avatar_num + 1
  end
end

app/views/shared/_choose_friends.html.erb
<div class="choose_friends">
  <div class="choose_friends_title">choose friends you want to share with:</div>
  <div class="choose_friends_list">
    <div class="row">
      <div class="nine columns">
        <table style="border-width:0px">
          <tr>
          <% @current_user.friends.each.with_index do |friend, index| %>
              <% if index !=0 && index % 5 == 0 then%> </tr><tr> <%end%>
              <td width="50px">
                <label><%= check_box_tag("friend_ids[]",friend.id) %><%= friend.name %></label>
              </td>
          <% end %>
          </tr>
        </table>
      </div>
      <div class="three columns"></div>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<div class="row comment">
<div class="comment_inside_frame">
  <div class="two column">
    <%= link_to(individual_path(comment.author), :method=>:get, :target=>"_blank") do%>
      <%= image_tag(comment.author.avatar_url, :size=>"90x90") %>
    <% end %>
  </div>
  <div class="ten column" id="comment_<%=comment.id%>">
      <div class="comment_author">
        <% if comment.author == @current_user %>
          <strong>
            <%= link_to("you", individual_path(comment.author), 
                        :method=>:get, :target=>"_blank") %>
          </strong> commented
        <% else %>
          <strong>
            <%= link_to(comment.author.name, individual_path(comment.author), 
                        :method=>:get, :target=>"_blank") %>
          </strong> commented 
        <% end %>
      </div> 
      <div class="comment_content">
        <%= comment.content %>
      </div>

      <ul class="block-grid two-up">
        <li class="comment_date"><%= comment.created_at %></li>
      <% no_reply ||= false %>
        <li class="reply_link">
        <% unless @current_user == comment.author %>
          <%= link_to("reply to #{comment.author.name}", 
                      new_reply_path(:comment_id => comment.id, :target_type=>"comment"), 
                      :target=>"_blank", :id=>"reply_link_#{comment.id}")%>
        <script type="text/javascript" charset="utf-8">
          $("#reply_link_<%=comment.id%>").attr("data-remote","true");
        </script>
        <% end %>
        </li>
      </ul>
      <div id="reply_box_<%=comment.id%>"></div>
      <% unless no_reply %>
        <%= render(:partial=>"shared/reply", 
                   :collection=>comment.replies) %>
      <% end %>
  </div>
</div>
</div>
    <br />


app/views/shared/_flash_info.html.erb
<% if flash[:notice] %>
  <div class="alert-box">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert-box error">
    <%= flash[:error] %>
  </div>
<% end %>
<% if flash[:success] %>
  <div class="alert-box success">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert-box warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(@user,:url => handle_path, 
             :method => method, :html=>{:class=>"nice"}) do |f| %>
  <%= render(:partial => "shared/form_errors", :object => @user) %>
    <%= f.label(:name, "name: ") %>
    <%= f.text_field(:name,:class=>"input-text") %>
    <%= f.label(:password, "password: ") %>
    <%= f.password_field(:password,:class=>"input-text") %>
    <%= f.label(:password_confirmation, "cofirm your password: ") %>
    <%= f.password_field(:password_confirmation,:class=>"input-text") %>
    <%= f.label(:email, "e-mail: ") %>
    <%= f.text_field(:email,:class=>"input-text") %>
    <br />
    <%= f.submit(button_name,:class=>"nice white radius button") %>
<% end %>
<hr />
Click <%= link_to("here to login",gate_path,:class=>"small white button") %>, if you have an account

app/views/shared/_form_errors.html.erb
<% target = form_errors %>
  <% if target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_reply.html.erb
<div class="reply">
<div class="row reply_inside_frame">
    <div class="two columns">
      <%= link_to(individual_path(reply.author), :method=>:get, :target=>"_blank") do%>
        <%= image_tag(reply.author.avatar_url, :size=>"70x70") %>
      <% end %>
    </div>
    <div class="ten columns">
      <div class="reply_auther">
        <% if reply.author == @current_user %>
          <strong>
            <%= link_to("you", individual_path(reply.author), 
                        :method=>:get, :target=>"_blank") %>
          </strong> replied 
        <% else %>
          <strong>
            <%= link_to(reply.author.name, individual_path(reply.author), 
                        :method=>:get, :target=>"_blank") %>
          </strong> replied
        <% end %>
      </div> 
      <div class="reply_content">
        <p><%= reply.content %></p>
      </div>
      <ul class="block-grid two-up">
        <li class="reply_date"><%= reply.created_at %></li>
        <li class="reply_link">
          <% unless @current_user == reply.author%>
            <%= link_to("reply to #{reply.author.name}", 
                        new_reply_path(:comment_id=>reply.id, :target_type=>"reply"), 
                        :id=>"reply_link_#{reply.id}", :target=>"_blank")%>
          <% end %>
          <script type="text/javascript" charset="utf-8">
            $("#reply_link_<%=reply.id%>").attr("data-remote","true");
          </script>
        </li>
      </ul>
      <div id="reply_box_<%=reply.id%>"></div>
    </div>
</div>
</div>

app/views/shared/_share_image_content.html.erb
<div class="share_content">
  <div class="image">
    <%= link_to(image_path(share.share_image), :id=>"image_#{share.share_image.id}", :target=>"_blank") do%>
      <%=image_tag(share.share_image.image.url(:medium))%>
    <% end %>
    <%= javascript_tag do %>
      $("#image_<%=share.share_image.id%>").attr("data-remote","true");
    <% end %>
  </div>
  <div class="description">
    <%= share.share_image.description %>
  </div>
</div>
<ul class="block-grid three-up">
  <li class="share_date">
    <%= share.created_at %>
  </li>
  <li class="share_link">
  <%= link_to(share.share_image.website_url,
              "http://#{share.share_image.website_url}/", :target=>"_blank") %>
  </li>
  <% is_button_disable ||= false %>
  <% unless is_button_disable%>
    <li class="comment_button">
      <%= link_to("Comment", new_comment_path(:share_info_id=>share.id),
                  :id=>"comment_button_#{share.id}", :target=>"_blank",
                  :class=>"white nice button radius")%>
    </li>
    <script type="text/javascript" charset="utf-8">
      $("#comment_button_<%=share.id%>").attr("data-remote","true");
    </script>
  <% end %>
</ul>

app/views/shared/_share_link_content.html.erb
<div class="share_content">
  <div class="title">
    <%= share.share_link.title %>
  </div>
  <div class="description">
    <%= share.share_link.description%>
  </div>
</div>
<ul class="block-grid three-up">
  <li class="share_date">
    <%= share.created_at %>
  </li>
  <li class="share_link">
  <%= link_to(share.share_link.website_url,
              "http://#{share.share_link.website_url}/", :target=>"_blank") %>
  </li>
  <% is_button_disable ||= false %>
  <% unless is_button_disable%>
    <li class="comment_button">
      <%= link_to("Comment", new_comment_path(:share_info_id=>share.id),
                  :id=>"comment_button_#{share.id}", :target=>"_blank",
                  :class=>"white nice button radius")%>
    </li>
    <script type="text/javascript" charset="utf-8">
      $("#comment_button_<%=share.id%>").attr("data-remote","true");
    </script>
  <% end %>
</ul>


app/views/shared/_share_text_content.html.erb
<div class="share_content"><%= share.share_text.content %></div>
<ul class="block-grid three-up">
  <li class="share_date">
    <%= share.created_at %>
  </li>
  <li class="share_link">
  <%= link_to(share.share_text.website_url,
              "http://#{share.share_text.website_url}/", :target=>"_blank") %>
  </li>
  <% is_button_disable ||= false %>
  <% unless is_button_disable%>
    <li class="comment_button">
      <%= link_to("Comment", new_comment_path(:share_info_id=>share.id),
                  :id=>"comment_button_#{share.id}", :target=>"_blank",
                  :class=>"white nice button radius")%>
    </li>
    <script type="text/javascript" charset="utf-8">
      $("#comment_button_<%=share.id%>").attr("data-remote","true");
    </script>
  <% end %>
</ul>

app/views/shared/_share_video_content.html.erb
<div class="share_content">
  <div class="video">
    <%= my_video_tag(share.share_video.video_url) %>
  </div>
  <div class="description">
    <%= share.share_video.description %>
  </div>
</div>
<ul class="block-grid three-up">
  <li class="share_date">
    <%= share.created_at %>
  </li>
  <li class="share_link">
  <%= link_to(share.share_video.website_url,
              "http://#{share.share_video.website_url}/", :target=>"_blank") %>
  </li>
  <% is_button_disable ||= false %>
  <% unless is_button_disable%>
    <li class="comment_button">
      <%= link_to("Comment", new_comment_path(:share_info_id=>share.id),
                  :id=>"comment_button_#{share.id}", :target=>"_blank",
                  :class=>"white nice button radius")%>
    </li>
    <script type="text/javascript" charset="utf-8">
      $("#comment_button_<%=share.id%>").attr("data-remote","true");
    </script>
  <% end %>
</ul>