config/routes.rb
ImmediateShare::Application.routes.draw do
  constraints(:id =>/\d+/) do
    root :to => 'share_infos#index'

    match "gate(/index)" => "gate#index", :via => :get, :as => :gate
    post "gate/login", :as => :login
    post "gate/logout", :as => :logout
    get "gate/register", :as => :register
    post "gate/create"

    scope :module => "admin" do
      scope "/admin" do
        resources :users do
          member do
            put "change_admin"
          end
        end
      end
    end

    resources :share_infos, :only => [:index, :new]

    match "share_infos/share_images/upload" => "share_infos/share_images#upload", :as=>:upload
    scope :module => "share_infos" do
      scope "/share_infos" do
        resources :share_texts, :as => :texts, :only =>[:new, :create]
        resources :share_images, :as => :images, :only => [:new, :create, :show]
        resources :share_videos, :as => :videos, :only => [:new, :create]
        resources :share_links, :as => :links, :only => [:new, :create]
      end
    end

    resources :friendships, :only => [:index, :destroy] do
      collection do
        get "search"
      end
      member do
        post "ask_for_friendship", :as => :ask
        post "agree_with_friendship", :as => :agree
      end
    end
    resources :individuals, :only => [:show, :edit, :update]
    scope :module => "individuals" do
      scope "/individuals" do
        resources :avatars, :as => :avatars, :only =>[:edit, :update, :create]
        resources :temps, :as => :temps, :only =>[:new, :create, :update], :path_names => {:new=>:crop}
      end
    end
    resources :comments, :only =>[:new, :create]
    resources :replies, :only =>[:new, :create]
    resources :system_messages, :only => [:index], :path_names => {:index => "unread"} do
      collection do
        get "all_messages", :as => :all
      end
      member do
        post "ignore"
      end
    end
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  before_save :save_inverse_friendship
  before_destroy :destroy_inverse_friendship

  validates :friend_id, :presence => true
  validates :user_id, :presence => true

  private 
  def save_inverse_friendship
    inverse_friendship = Friendship.new(:user_id => friend_id,
                                        :friend_id => user_id)
    Friendship.skip_callback(:save, :before, :save_inverse_friendship)
    inverse_friendship.save()
    Friendship.set_callback(:save, :before, :save_inverse_friendship)
  end
  def destroy_inverse_friendship
    inverse_friendship = Friendship.find(:first, :conditions => ["user_id = :friend_id and friend_id = :user_id", {:friend_id => friend_id, :user_id => user_id}])
    if inverse_friendship
      inverse_friendship.delete() #bypass before_destroy callback
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  #before_filter :get_current_user, :authenticate, :get_system_message 
  #(in application_controller)

  # GET /friendships
  # GET /friendships.json
  def index
    @users = User.all
  end

  def ask_for_friendship
    friend = User.find_by_id(params[:id])
    if friend && \
      SystemMessage.create_message(@current_user.id, params[:id].to_i,
                                   "ask_friendship")
      flash[:notice] = "Please wait for #{friend.name}'s reply"
    else
      flash[:error] = "fail, please try again"
    end
    redirect_to(:back)
  end

  def agree_with_friendship
    friend = User.find_by_id(params[:id])
    if friend && create_friendship_with(friend.id)
      SystemMessage.create_message(@current_user.id, params[:id].to_i,
                                   "agree_friendship")
      SystemMessage.mark_message_read(params[:message_id])
      flash[:success] = "#{friend.name} is your friend now"
    else
      flash[:error] = "failed to add friend"
    end
    redirect_to(:back)
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = @current_user.friendships.find_by_id(params[:id])
    if @friendship.destroy
      flash[:success] = "This relationship has been deleted"
    else
      flash[:error] = "Delete failed, if you really want, please try again"
    end
    redirect_to(individual_path(@current_user))
  end

  def search
    @is_search_result = true
    @users = User.find(:all, 
              :conditions=>["users.name like ?", "%#{params[:user_name]}%"])
    flash[:original_uri] = request.original_fullpath
    render(:action => "index")
  end

  private

  def create_friendship_with friend_id
    friendship = @current_user.friendships.build(:friend_id => friend_id) 
    if friendship.save()
      return true
    else
      return false
    end
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_user_list.html.erb
<div class="friend_list">
<% @users.each do |user| %>
  <% unless @current_user.id == user.id %>
    <% if @current_user.friends.include?(user) %>
      <% is_friend = true %>
    <% end %>
    <div class="row friend_term">
      <div class="three columns">
        <%= image_tag(user.avatar_url, :width=>50) %>
      </div>
      <div class="seven columns friend_info">
        <%= user.name %>(<%= is_friend ? "friend" : "stranger" %>)
      </div>
      <div class="two columns">
        <% if is_friend %>
          <%= button_to("add", ask_friendship_path(:id => user.id), 
                        :disabled => true, 
                        :class=>"nice black radius button") %>
        <% else %>
          <%= button_to("add", ask_friendship_path(:id => user.id),
                        :class=>"nice blue radius button") %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<%= page_title("Search Friends") %>

<div id="search">
  <%= form_tag(search_friendships_path, :method => :get,
               :class=>"nice") do %>
    <div class="search_title">Search</div>
    <div class="search_field">
        <%=text_field_tag("user_name", "", :placeholder=>"user name", 
                                  :class=>"input-text") %>
    </div>
    <div class="search_button">
      <%= image_submit_tag("search_button.png", :name => nil)%>
    </div>
  <% end %>
</div>
<% if @users.blank? %>
  <h4>Sorry, no record has been found</h4>
<% else %>
  <%= render("user_list") %>
<% end %>

<% if @is_search_result %>
  <%= link_to("Go back to all users", friendships_path) %>
<% end %>

<br />

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>